# Generated by Django 5.0.6 on 2024-07-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogcore', '0007_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bookmarks',
            new_name='bookmark',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to='Blogcore.post'),
        ),
    ]
