# Generated by Django 5.0.6 on 2024-07-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogcore', '0008_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
