# Generated by Django 5.0.6 on 2024-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogcore', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='default/default-user.jpg', null=True, upload_to='image'),
        ),
    ]
