# Generated by Django 5.0.6 on 2024-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogcore', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
