# Generated by Django 5.0.6 on 2024-07-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogcore', '0024_alter_comment_options_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
